"""billing

Revision ID: 598ae27864c2
Revises: 97a4f43a8f8c
Create Date: 2026-05-13 17:32:49.334971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598ae27864c2'
down_revision: Union[str, Sequence[str], None] = '97a4f43a8f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('free', 'pro', 'team', name='userplan'), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('billing_interval', sa.Enum('monthly', 'yearly', name='billing_interval'), nullable=False),
    sa.Column('max_projects', sa.Integer(), nullable=True),
    sa.Column('max_documents_per_project', sa.Integer(), nullable=True),
    sa.Column('max_queries_per_month', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('stripe_price_id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'past_due', 'expired', name='subscription_status'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queries_this_period', sa.Integer(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('user_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('openai', 'anthropic', 'gemini', 'ollama', name='llm_provider'), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('key_hint', sa.String(length=4), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_api_keys_id'), 'user_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_user_api_keys_user_id'), 'user_api_keys', ['user_id'], unique=False)
    op.create_index('uq_user_api_keys_user_provider', 'user_api_keys', ['user_id', 'provider'], unique=True)
    op.create_table('token_usage_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('query_history_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('openai', 'anthropic', 'gemini', 'ollama', name='llm_provider'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd_micros', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['query_history_id'], ['query_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_log_created_at'), 'token_usage_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_log_id'), 'token_usage_log', ['id'], unique=False)
    op.create_index(op.f('ix_token_usage_log_project_id'), 'token_usage_log', ['project_id'], unique=False)
    op.create_index(op.f('ix_token_usage_log_provider'), 'token_usage_log', ['provider'], unique=False)
    op.create_index(op.f('ix_token_usage_log_query_history_id'), 'token_usage_log', ['query_history_id'], unique=False)
    op.create_index('ix_token_usage_log_user_created', 'token_usage_log', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_log_user_id'), 'token_usage_log', ['user_id'], unique=False)
    op.create_index('ix_token_usage_log_user_provider_created', 'token_usage_log', ['user_id', 'provider', 'created_at'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_token_usage_log_user_provider_created', table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_user_id'), table_name='token_usage_log')
    op.drop_index('ix_token_usage_log_user_created', table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_query_history_id'), table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_provider'), table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_project_id'), table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_id'), table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_created_at'), table_name='token_usage_log')
    op.drop_table('token_usage_log')
    op.drop_index('uq_user_api_keys_user_provider', table_name='user_api_keys')
    op.drop_index(op.f('ix_user_api_keys_user_id'), table_name='user_api_keys')
    op.drop_index(op.f('ix_user_api_keys_id'), table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
